server:
  service:
    type: ClusterIP

  extraArgs:
    - --insecure

  ingress:
    enabled: true

    # 차트에서 GKE ingress 옵션 분기하려면 controller를 gke로 주는 게 안전
    controller: gke

    ingressClassName: gce
    annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.global-static-ip-name: "${static_ip_name}"

    hostname: "${host}"   # hosts: 가 아니라 hostname:
    path: /
    pathType: Prefix
